import type { Metadata } from "next";
import {
  Plus_Jakarta_Sans,
  Montserrat_Alternates,
  Space_Grotesk,
} from "next/font/google";
import "./globals.css";
import HomeProvider from "./provider";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const montserratAlternates = Montserrat_Alternates({
  variable: "--font-montserrat-alternates",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Flexmode Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${montserratAlternates.variable} antialiased font-primary`}
      >
        <HomeProvider>{children}</HomeProvider>
      </body>
    </html>
  );
}
